nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - arabox-landing-pull
  ingress:
    enabled: false
    class:
    domain: arabox-test.westerops.com
    sslRedirect: true

arabox_test:
  api_url: 'https://smartdashboardlanding.arabox-test.westerops.com/'
  replicas: 1
  nameSuffix: frontend
  hostPrefix: smartdashboardlanding.arabox-test
  appKubernetesIoService: smartdashboard-landing
  port: 3000
  image: registry.docker.dev.westerops.com/arabox-landingpage:v7
  resources:
    limits:
      memory: 1Gi
      cpu: 250m
    requests:
      memory: 250Mi
      cpu: 100m

